### ISSUE TITLE
ERROR:  While executing gem ... (Errno::EACCES)

### ISSUE THREAD

**Issue by exuperok** [fideloper/Vaprobash#458]
I get this error while executing vagrant up following the install instruction from the documentation

`==> Vaprobash: >>> Start installing Ruby Gems
==> Vaprobash: ERROR:  While executing gem ... (Errno::EACCES)
==> Vaprobash:     Permission denied - /var/lib/gems
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod +x /tmp/vagrant-shell && /tmp/vagrant-shell "latest" "sass" "compass"`

**Comment by fideloper** [comment]
Is this from installing `rvm.sh` shell script or something else that depending on Ruby?

**Comment by exuperok** [comment]
yes, here is the full log

==> Vaprobash: /tmp/vagrant-shell: line 48: /home/vagrant/.rvm/scripts/rvm: No such file or directory
==> Vaprobash: >>> Start installing Ruby Gems
==> Vaprobash: ERROR:  While executing gem ... (Errno::EACCES)
==> Vaprobash:     Permission denied - /var/lib/gems
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod +x /tmp/vagrant-shell && /tmp/vagrant-shell "latest" "sass" "compass"

**Comment by FDiskas** [comment]
I got the same problem
---
```
 /tmp/vagrant-shell: line 48: /home/vagrant/.rvm/scripts/rvm: No such file or directory
==> Vaprobash: ERROR:  While executing gem ... (Errno::EACCES)
==> Vaprobash: Permission denied @ dir_s_mkdir - /var/lib/gems
The SSH command responded with a non-zero exit status.
```

**Comment by FDiskas** [comment]
```
==> : >>> Start installing Ruby Gems
==> : Successfully installed sass-3.4.13
==> : Building native extensions.  This could take a while...
==> : ERROR:  Error installing compass:
==> :    ERROR: Failed to build gem native extension.
==> :
==> :         /usr/bin/ruby1.9.1 extconf.rb
==> : /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
==> :    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
==> :    from extconf.rb:4:in `<main>'
==> :
==> :
==> : Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.8 for inspection.
==> : Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.8/ext/ffi_c/gem_make.out
```

**Comment by FDiskas** [comment]
I tried after installing the ruby
```
sudo apt-get install ruby-dev
```
this is for additional files to build executables. And its worked

**Comment by thibmaek** [comment]
Same error but strangely enough only for Compass

**Comment by cmosguy** [comment]
@fideloper @exuperok 

I recently encountered this error and i have included that the entire RVM system install gets botched because I was trying to install a key behind my companies firewall.  The command:

```bash
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
```

Uses the port 11371 which is blocked by the firewall.  What actually worked was using the recommended command to get this key:

```bash
command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
```

then i could do:
```bash
\curl -sSL https://get.rvm.io | bash -s stable --ruby
```

After which I could get ruby > 2.0.

Is it possible if we could modify the Vaprobash scripts to support this command instead?

Thanks,
Adam

**Comment by fideloper** [comment]
Gotcha - yeah that sounds like a good alternative.

**Comment by exuperok** [comment]
@cmosguy  thanks for this, itworked for me!
